dockers/alpine/classycle/Dockerfile, dockers/alpine/findbugs/Dockerfile, dockers/alpine/phpcheckstyle/Dockerfile
findbugs, classycle, phpcheckstyle, tslint
//phpcheckstyle requires composer.json
//findbugs requires linter archive in root
//classycle requires linter archive in root
=> 4 new linters

templates/composer-no_https/composer.json
composer.json (turn off https)
=> template for composer - no_https

dockers/alpine/lizard/Dockerfile, dockers/alpine/pmd/Dockerfile, dockers/alpine/sonar/Dockerfile, dockers/alpine/vnu/Dockerfile
Needs vnu.tar archive to work (ask me)
Work directory is /vnu/
#Tested with "java -jar vnu.jar --help"
=> v.NU docker added

bin/lh_engine.sh, bin/lh_main.sh
=> Add opportunity to specify custom command

hub/.schema/@type.area.json, hub/.schema/@type.language.json, hub/.schema/@type.license.json, hub/.schema/@type.manager.json, hub/.schema/@type.param.json, hub/.schema/args.json, hub/.schema/deps.json, hub/.schema/engine.json, hub/jshint/args.json, hub/jshint/deps.json, hub/jshint/engine.json
jshint example updated as well
=> Improve schemas for linterhub and split by types

hub/brakeman/args.json, hub/brakeman/engine.json, hub/checkstyle/engine.json
Add metadata for checkstyle engine,
Add metadata and arguments for brakeman engine
=> Add brakeman and checkstyle engines

engine/markdownlint/args.json, engine/markdownlint/deps.json, engine/markdownlint/meta.json
=> Add support for markdown engine #41

engine/jsonlint/args.json, engine/jsonlint/deps.json, engine/jsonlint/meta.json
=> Move jsonlint engine to engine/, fix all components

engine/remark-lint/args.json, engine/remark-lint/deps.json, engine/remark-lint/meta.json
=> Add support for remark-lint engine #39

engine/stylint/args.json, engine/stylint/deps.json, engine/stylint/meta.json
=> add support for stylint engine #30

engine/sass-lint/args.json, engine/sass-lint/deps.json, engine/sass-lint/meta.json
=> Add support for sass-lint engine #36

engine/html-inspector/args.json, engine/html-inspector/deps.json, engine/html-inspector/meta.json
=> Add support for html-inspector engine #40

schema/language.json
=> Add OOCSS language #55

engine/csslint/args.json, engine/csslint/deps.json, engine/csslint/meta.json
=> Add support for csslint engine #33

engine/colorguard/args.json, engine/colorguard/deps.json, engine/colorguard/meta.json
=> Add support for colorguard engine №28

engine/stylelint/args.json, engine/stylelint/deps.json, engine/stylelint/meta.json
=> Add support for stylelint engine #32

engine/proselint/args.json, engine/proselint/deps.json, engine/proselint/meta.json
=> Add support for proselint engine #38

engine/polylint/args.json, engine/polylint/deps.json, engine/polylint/meta.json
=> Add support for polylint engine #79

engine/eslint/args.json, engine/eslint/deps.json, engine/eslint/meta.json
=> Add support for eslint engine #75

engine/tslint/args.json, engine/tslint/deps.json, engine/tslint/meta.json
=> Add support for tslint engine #78

engine/xo/args.json, engine/xo/deps.json, engine/xo/meta.json
Add support for xo engine
Closes https://github.com/repometric/linterhub/issues/70
=> Add support for xo engine (test)

engine/tslint/deps.json
Add typescript dependency for tslint engine
Closes https://github.com/repometric/linterhub/issues/78
=> Add typescript dependency

engine/jslint/args.json, engine/jslint/deps.json, engine/jslint/meta.json
Add jslint engine
Closes #66 .
=> Add jslint engine

engine/coffeelint/args.json, engine/coffeelint/deps.json, engine/coffeelint/meta.json
Coffeelint engine has been added
Closes #63
=> Add coffeelint engine

engine/scss-lint/args.json, engine/scss-lint/deps.json, engine/scss-lint/meta.json
scss-lint engine has been added
Closes #37
=> Add scss-lint engine

engine/standard/args.json, engine/standard/deps.json, engine/standard/meta.json
Standard engine has been added
Closes #69
=> Add standard engine

engine/htmlhint/args.json, engine/htmlhint/deps.json, engine/htmlhint/meta.json
htmlhint engine has been added
Closes #111
=> Add htmlhint engine

schema/platform.json
pacman package manager has been added
Closes #114
=> add pacman package manager

engine/pug-lint/args.json, engine/pug-lint/deps.json, engine/pug-lint/meta.json
Pug-lint engine has been added
Closes #113 .
=> Add pug-lint engine

schema/platform.json
Add Chocolatey package manager
Closes #119 .
=> Add Chocolatey package manager

schema/language.custom.json
Apache Velocity language has been added
Closes #124
=> Add Apache Velocity language

engine/pmd/args.json, engine/pmd/deps.json, engine/pmd/meta.json
Pmd engine has been added
Closes #86
=> Add pmd engine

engine/bandit/args.json, engine/bandit/deps.json, engine/bandit/meta.json
Bandit engine has been added
Closes #127
=> Add bandir engine

engine/brakeman/args.json, engine/brakeman/deps.json, engine/brakeman/meta.json
Brakeman engine has been added.
Closes #129 .
=> Add brakeman engine

engine/flake8/args.json, engine/flake8/deps.json, engine/flake8/meta.json
Flake8 engine has been added
Closes #133
=> Add flake8 engine

engine/pmd/deps.json, engine/xo/deps.json, schema/args.json, schema/deps.json, schema/meta.json, schema/platform.json
Closes https://github.com/repometric/linterhub/issues/135
=> Update schemas according to EPs

schema/language.custom.json
CoffeeCup language has been added
Closes #139 .
=> Add CoffeeCup language

schema/language.custom.json
JEDI language has been added
Closes #138
=> Add JEDI language

engine/jscs/args.json, engine/jscs/deps.json, engine/jscs/meta.json, schema/language.custom.json
JSCS engine has been added
Closes #72 .
=> Add jscs engine

engine/lizard/args.json, engine/lizard/deps.json, engine/lizard/meta.json
Lizard engine has been added
Closes #80
=> Add lizard engine

engine/gendarme/args.json, engine/gendarme/deps.json, engine/gendarme/meta.json
gendarme engine has been added
Closes #88
=> Add gendarme engine

engine/ccm/args.json, engine/ccm/deps.json, engine/ccm/meta.json
ccm engine has been added
Closes #62 .
=> Add ccm engine

engine/pylint/args.json, engine/pylint/deps.json, engine/pylint/meta.json
pylint engine has been added
Closes #150
=> Add pylint engine

engine/ocstyle/args.json, engine/ocstyle/deps.json, engine/ocstyle/meta.json
ocstyle engine has been added
Closes #161 .
=> add ocstyle engine

engine/pycodestyle/args.json, engine/pycodestyle/deps.json, engine/pycodestyle/meta.json
pycodestyle engine has been added
Closes #152
=> Add pycodestyle engine

engine/checkstyle/args.json, engine/checkstyle/deps.json, engine/checkstyle/meta.json
Checkstyle engine has been added
Closes #145
=> Add checkstyle engine

engine/pyflakes/args.json, engine/pyflakes/deps.json, engine/pyflakes/meta.json
pyflakes engine has been added
Closes #151
=> add pyflakes engine

engine/radon/args.json, engine/radon/deps.json, engine/radon/meta.json
RAdon engine has been added
Closes #149
=> Add radon engine

engine/ruby-lint/args.json, engine/ruby-lint/deps.json, engine/ruby-lint/meta.json
Ruby-lint engine has been added
Closes #147
=> Add ruby-lint engine

engine/flay/args.json, engine/flay/deps.json, engine/flay/meta.json
Flay engine has been added
Closes #164
=> Add flay engine

engine/sitevalidator/args.json, engine/sitevalidator/deps.json, engine/sitevalidator/meta.json
Sitevalidator engine has been added.
Closes #89
=> Add sitevalidator engine

engine/vnu/args.json, engine/vnu/deps.json, engine/vnu/meta.json
vnu engine has been added
Closes #85
=> Add vnu engine

engine/puppet-lint/args.json, engine/puppet-lint/deps.json, engine/puppet-lint/meta.json
Puppet-lint engine has been added
Closes #153
=> Add puppet-lint engine

engine/classycle/args.json, engine/classycle/deps.json, engine/classycle/meta.json
Classycle engine has been added
Closes #166
=> Add classycle engine

engine/lesslint/args.json, engine/lesslint/deps.json, engine/lesslint/meta.json
`Description of the pull request.`
Lesslint engine has been added
Closes #35
=> Add lesslint engine

engine/findbugs/args.json, engine/findbugs/deps.json, engine/findbugs/meta.json
Findbugs engine has been added
Closes #165
=> Add findbugs engine

engine/csslint/meta.json
grunt-lesslint has been added
Closes #189
=> Add grunt-lesslint engine

engine/findbugs/meta.json
Spotbugs has been added
Closes #188
=> Add spotbugs engine

engine/pmd/meta.json
cpd engine has been added
Closes #64
=> Add cpd engine

engine/pycodestyle/meta.json
pep8 engine has been added
Closes #200
=> Add pep8 engine

engine/jedi/args.json, engine/jedi/deps.json, engine/jedi/meta.json
Jedi engine has been added
Closes #199
=> Add jedi engine

engine/codesniffer/args.json, engine/codesniffer/deps.json, engine/codesniffer/meta.json
codesniffer engine has been added
Closes #160
=> Add codesniffer engine

engine/codesniffer/args.json
Prefixes in args.json were fixed
Closes #208
=> Fix prefixes in args.json

engine/clinton/args.json, engine/clinton/deps.json, engine/clinton/meta.json
Clinton engine has been added
Closes #206
=> Add clinton engine

engine/prettier/args.json, engine/prettier/deps.json, engine/prettier/meta.json
Prettier engine has been added
Closes #204 `.
=> Add prettier engine

engine/phpmd/args.json, engine/phpmd/deps.json, engine/phpmd/meta.json
phpmd engine has been added
Closes #157
=> Add phpmd engine

engine/phpmetrics/args.json, engine/phpmetrics/deps.json, engine/phpmetrics/meta.json
phpmetrics engine has been added
Closes #156
=> Add phpmetrics engine

engine/phpsa/args.json, engine/phpsa/deps.json, engine/phpsa/meta.json
phpsa engine has been added
Closes #155
=> Add phpsa engine

engine/uncrustify/args.json, engine/uncrustify/deps.json, engine/uncrustify/meta.json
uncrustify engine has been added
Closes #207
=> Add ucrustify engine

schema/extr.json
Closes https://github.com/repometric/linterhub/issues/243
=> Add extr.json schema

schema/extr.json
Success field has been deleted
Closes #246
=> Delete success field

engine/jshint/extr.json, engine/jshint/reporter.js
Reporter file and extr.json have been added 
Closes #220
=> Add reporter and extr.json for jshint

engine/coffeelint/extr.json, engine/coffeelint/reporter.coffee
Reporter and extr.json for coffeelint have been added
Closes #236
=> Add reporter and extr.json for coffeelint

engine/coffeelint/reporter.coffee
md5 has been deleted
Closes #260
=> Delete md5 from reporter for coffeelint

engine/coffeelint/args.json
Delimeters has been added to args.json for coffeelint
Closes #259
=> Add delimeters to args.json for coffeelint

schema/extr.json
engine field has been added and executable field has been removed
Closes #267
=> Add engine field to schema/extr.json and remove executable field

engine/coffeelint/pipe.json, engine/jshint/args.json, engine/jshint/pipe.json
=> Rename file extr to pipe

engine/phpcodefixer/args.json, engine/phpcodefixer/deps.json, engine/phpcodefixer/meta.json
phpcodefixer engine has been added.
Closes https://github.com/repometric/linterhub/issues/276
=> Add phpcodefixer engine

engine/phpcpd/args.json, engine/phpcpd/deps.json, engine/phpcpd/meta.json
phpcpd engine has been added.
Closes https://github.com/repometric/linterhub/issues/280
=> Add phpcpd engine

engine/jsonlint/args.json, engine/jsonlint/pipe.json, engine/jsonlint/reporter.js
=> Implement reporter for jsonlint engine

engine/csslint/pipe.json, engine/csslint/reporter.js
=> Implement reporter for csslint engine

engine/htmlhint/pipe.json, engine/htmlhint/reporter.js
=> feat: implement reporter for htmlhint engine (#234)

engine/jslint/pipe.json, engine/jslint/reporter.js
=> feat: Implement reporter for jslint engine (#221)
